# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: product-service
  labels:
    app: product-service

type: Opaque

# stringData convierte autom√°ticamente a base64
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"