# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: user-service
  labels:
    app: user-service

type: Opaque

# stringData convierte autom√°ticamente a base64
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"